### ISSUE TITLE
Crash during Qonversion.offerings()

### ISSUE THREAD

**Issue by AlexLionne** [qonversion/react-native-sdk#208]
Since outage on your plateform (01/16/2023) it seems that offering can't be fetched and produce a crash (at least on iOS)

I'm not able to catch this crash

```
dispatch(setOffers({}))
      
Qonversion.offerings()
  .then((shop) => {
    if (shop) {
       dispatch(setOffers(shop))
    }
  })
  .catch(error => console.error(error))

// Qonversion.restore().catch is returning an internal server error as expected
```

This always produces a crash with this trace (i'm not familiar with Xcode debugger)

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/8268621/212752577-eeaf0442-0a46-4da6-998e-f9641e8509d8.png">

Do you think that using this is a good workaround for now ? 

```
await axios.get('https://api.qonversion.io/')
        .catch(e => {
          //
          if (e.message.includes('502') || e.message.includes('503')) {
            isQonversionAvailable = false
          }
        })
```

I'm initializing SDK as in the docs
 
```
const config = new QonversionConfigBuilder(
  'xxxxxx...',
  LaunchMode.SUBSCRIPTION_MANAGEMENT
)
  .setEntitlementsCacheLifetime(EntitlementsCacheLifetime.YEAR)
  .build()

Q.initialize(config)

const Qonversion = Q.getSharedInstance()

export { Qonversion }
```

**RN 0.70.5**
**Qonversion SDK 4.0.1**

Thank you

**Comment by SpertsyanKM** [comment]
Hello! Thank you for contacting us! First of all, I want to apologize for the inconvenience provided by this outage. All our team is hard working on solving this problem. All the actual information is available on our [status-page](https://status.qonversion.io/).

Speaking of your issue, could you please clarify whether you see this exception on a new install or on an existing app (launched before the outage started)? It's important because if Qonversion had successfully launched at least once before the outage, fault tolerance mechanics begin working when something goes wrong later.

Also, could you please provide us with a complete stack trace (starting from the first line)?

**Comment by SpertsyanKM** [comment]
Speaking of the workaround, it looks suitable but only as a temporary solution for the current outage. As it affects the whole API. But in general, you should rely on Qonversion SDK responses and handle errors from calls. If there is really some kind of problem causing exceptions on our side, we will fix it as soon as possible. In a normal way even if our API is facing problems, the SDK will try to respond to your calls using its own caches where possible or will return an error otherwise.

**Comment by AlexLionne** [comment]
> could you please clarify whether you see this exception on a new install or on an existing app


On an existing app (successfully working before outage)

I will try to provide a better trace

Good luck in this difficult situation

**Comment by SpertsyanKM** [comment]
Thank you a lot! 🙏 

Looking forward for the details.

**Comment by AlexLionne** [comment]
All services we need are up ! 
It seems I can't provide any stack trace.
I can close this issue and hope that `.offerings()` will not crash when api can't be reached. 
Thanks again

**Comment by SpertsyanKM** [comment]
Yes, we were able to solve our API problem. Well, we will try to investigate this problem ourselves and fix it, if the problem is on our side. Thank you again for reporting this issue!

**Comment by SpertsyanKM** [comment]
We have detected the problem causing described crashes and fixed it. Please, update your SDK version to [4.0.2](https://github.com/qonversion/react-native-sdk/releases/tag/4.0.2), where this crash won't appear.
